### PR TITLE
audio route to speaker

### PR DESCRIPTION
**Pull request by jibon57**
In iPhone 6s audio was playing in ear speaker instated of loudspeaker. This will resolve the issue.

### CODE REVIEW

**Comment by jibon57** [comment]
@NathanaelA Will you please check it & merge?

**Comment by NathanaelA** [comment]
Why is it a problem that the audio plays on your headphones if they are connected?    I would think that is the expected behavior.

**Comment by jibon57** [comment]
@NathanaelA It's not headphone it's earspeaker (When we talk) the top one.

**Comment by NathanaelA** [comment]
1. Did you mean to close this?
2. I'm not sure I follow what the issue is then.  Can you describe what you are seeing and why setting this fixes it.  I looked up the code and didn't seem to see the point of it.

**Comment by jibon57** [comment]
@NathanaelA Sorry, the solution I wanted to provide wasn't perfect. I am working to resolve the problem. In this pull sound was routed to speaker even you are using headset. So, this is wrong solution. This should be the solution:

```
let audioSession = AVAudioSession.sharedInstance();
		let output = audioSession.currentRoute.outputs.lastObject.portType.match(/Speaker/);
		if (output) {
		  	try {
		    	audioSession.setCategoryError(AVAudioSessionCategoryPlayAndRecord);
		        audioSession.overrideOutputAudioPortError(AVAudioSessionPortOverrideSpeaker);
		        audioSession.setActiveError(true);
		        //console.log("audioSession category set and active");
		    } catch (err) {
		        //console.log("setting audioSession category failed");
		    }
		}
```
Actually main problem with iPhone 6s & iPhone 5s ( I have this 2 only not sure other). When you I was trying to play video it was playing in earspeaker ( the speaker we use to hear during talking) not in loudspeaker. But from iPad it was working fine because that don't have earspeaker. That was the problem & I am looking for the solution. I hope the above code will be the solution. I am still testing. You can have a look too.

**Pull request closed without merging**
